/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DivButton: typeof import('./../src/components/shared/DivButton/DivButton.tsx')['default']
    Footer: typeof import('./../src/components/shared/Footer/Footer.vue')['default']
    Navbar: typeof import('./../src/components/shared/Navbar/Navbar.vue')['default']
  }
}
