name: E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
#     steps:
#     - name: Install Playwright
#       run: npx playwright install --with-deps

#     - name: Run e2e tests
#       run: npm run test:e2e

#     - uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
